
FROM alpine:3.9

LABEL maintainer="x@gmail.com"


RUN apk add --update-cache \
    python3 \
    python-dev \
    py-pip \
    build-base \
&& pip install Click==7.0 && itsdangerous==1.1.0 && Flask==1.0.2 &&  Jinja2==2.10 && MarkupSafe==1.1.1 && Werkzeug==0.14.1
WORKDIR /app

EXPOSE 5000

ADD app.py /

CMD [ "python", "./app.py" ]



